#!/bin/bash
cp starter-code/UCSDGraphs/src/basicgraph/{Graph.java,GraphAdjList.java,GraphAdjMatrix.java} . && zip part_2.zip Graph.java GraphAdjList.java GraphAdjMatrix.java && rm Graph.java GraphAdjList.java GraphAdjMatrix.java
